### ISSUE TITLE
CSS hyphenation

### ISSUE THREAD

**Issue by hlfcoding** [NixOS/nixos-homepage#22]
On the home page especially, for non-widescreen window sizes, the columns can get too narrow and cause irregular whitespacing and readability problems. While this does not fix it in Chrome because it's not supported, this would adequately address the issue for now:
```css
p {
  -webkit-hyphens: auto;
  -moz-hyphens: auto;
  hyphens: auto;
}
```
